### ISSUE TITLE
Code description

### ISSUE THREAD

**Issue by maverickjia** [Hammerling-Research-Group/placement#4]
From Dr. Hammerling:
Hi Meng, can you please work with Philip on synthesizing your sensor placement optimization work for the research webpage? One or two paragraphs that make it understandable for a broader audience, can be a bit like a story, and maybe one or two figures. And then there will be a link to the preprint for the audience interested in the technical details, as well as the github code. Philip, please work with Meng and Kiran on prioritizing this code.

**Comment by pdwaggoner** [comment]
Done: https://ams.mines.edu/hammerling-research-group/research/placement/
